// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBltTLvG8A5m5dZXANFmRBSJYCjEgcJtuc',
    appId: '1:970364248784:web:06db0accf624838cb074d5',
    messagingSenderId: '970364248784',
    projectId: 'teamdream-f8a59',
    authDomain: 'teamdream-f8a59.firebaseapp.com',
    databaseURL: 'https://teamdream-f8a59-default-rtdb.firebaseio.com',
    storageBucket: 'teamdream-f8a59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6SKxGQiPamG4wDesSGfHIP6XD4T52Ouc',
    appId: '1:970364248784:android:f189095bf0684f5bb074d5',
    messagingSenderId: '970364248784',
    projectId: 'teamdream-f8a59',
    databaseURL: 'https://teamdream-f8a59-default-rtdb.firebaseio.com',
    storageBucket: 'teamdream-f8a59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP-YKLJXVEP2aq47BPtLdOWA8K3Tyk8j0',
    appId: '1:970364248784:ios:8545518612d84369b074d5',
    messagingSenderId: '970364248784',
    projectId: 'teamdream-f8a59',
    databaseURL: 'https://teamdream-f8a59-default-rtdb.firebaseio.com',
    storageBucket: 'teamdream-f8a59.firebasestorage.app',
    iosBundleId: 'com.example.sleepApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP-YKLJXVEP2aq47BPtLdOWA8K3Tyk8j0',
    appId: '1:970364248784:ios:8545518612d84369b074d5',
    messagingSenderId: '970364248784',
    projectId: 'teamdream-f8a59',
    databaseURL: 'https://teamdream-f8a59-default-rtdb.firebaseio.com',
    storageBucket: 'teamdream-f8a59.firebasestorage.app',
    iosBundleId: 'com.example.sleepApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBltTLvG8A5m5dZXANFmRBSJYCjEgcJtuc',
    appId: '1:970364248784:web:e4906d3a4b6dd614b074d5',
    messagingSenderId: '970364248784',
    projectId: 'teamdream-f8a59',
    authDomain: 'teamdream-f8a59.firebaseapp.com',
    databaseURL: 'https://teamdream-f8a59-default-rtdb.firebaseio.com',
    storageBucket: 'teamdream-f8a59.firebasestorage.app',
  );
}
